apiVersion: v1
kind: Pod
metadata:
  name: downward-api-pod-env
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'env && sleep 3600']
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
              fieldPath: spec.nodeName
      - name: HOST_IP
        valueFrom:
          fieldRef:
              fieldPath: status.hostIP
      - name: POD_IP
        valueFrom:
          fieldRef:
              fieldPath: status.podIP