apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: main-container
    image: nginx:latest
  initContainers:
  - name: init-checkapi
    image: curlimages/curl:latest
    command:
    - sh
    - -c 
    - |
      echo "Checking API availability..."
      sleep 10 
      until curl -s https://kubernetes.io > /dev/null; do
        echo "API server is not available yet. Retrying in 5 seconds..."
        sleep 5
      done
      echo "API server is available. Proceeding with main container."